name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lintpr:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: "Validate title"
        uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: "Validate branch"
        uses: Vankka/pr-target-branch-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: "master staging"
          exclude: development # Don't prevent going from development -> main
          comment: "PRs cannot target `master` and `staging` branches, please target `development` branch instead"
