name: 'Staging changelog'

on:
  push:
    branches:
      - staging

jobs:
  changelog:
    # if: startsWith(github.event.head_commit.message, 'Merge branch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bump tag
        id: bump_tag
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-commit: "true"
          output-file: "false"
          fallback-version: "1.56.0"

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3
        if: ${{ steps.bump_tag.outputs.skipped == 'false' }}
        with:
          configuration: "changelog.config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ steps.bump_tag.outputs.tag }}
          body: ${{steps.changelog.outputs.changelog}}
      

      - name: Label PRs'
        uses: ./actions/label_prs
        id: label_prs
        with:
          label: 'Foobar'
          prs: ${{steps.changelog.outputs.pull_requests}}
